runtime: python39
entrypoint: gunicorn -b :$PORT api.main_production:app

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  ENVIRONMENT: production
  API_HOST: 0.0.0.0
  API_PORT: 8080
  API_RELOAD: false
  DEBUG: false
  LOG_LEVEL: INFO

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto 